import img1 from "../assets/img1.jpeg";
import img2 from "../assets/img2.jpeg";
import img3 from "../assets/img3.jpeg";
import img4 from "../assets/img4.jpeg";
import img5 from "../assets/img5.png";
import img6 from "../assets/img6.jpeg";
import img7 from "../assets/img7.png";

const products = [
{
    id: 5,
    name: "7.4 kW AC EV Charger",
    power: "7.4 kW",
    type: "Type 1",
    price: "50,000",
    sku: "PROD-AC5U2F",
    category: "ac",
    image: "7.4kw",
    available: "In Stock (50 units)",
    color: "white",
    src: img5,
    description: "The 7.4kW AC EV Charger is designed for residential and commercial use, offering a reliable and safe charging experience for electric vehicles. With its compact design, smart control features, and energy efficiency, this charger is ideal for home garages, offices, and small-scale EV charging networks.",
    specs: [
    "Output Power: 7.4 kW",
    "Output Voltage: 230V AC (Single Phase)",
    "Output Current: 32A",
    "Connector Type: Type-2 (IEC 62196-2)",
    "Charging Mode: Mode 3 (IEC 61851)",
    "Communication Protocol: OCPP 1.6 JSON",
    "Network Connectivity: Wi-Fi / Ethernet / 4G (Optional)",
    "OEM: Ecoplug Energy India Limited",
    "Installation: Wall Mount / Pedestal",
    "User Access: RFID / Mobile App (Optional)",
    "Frequency: 50/60Hz",
    "Cable Length: 5m standard",
    "User Interface : LED Status Indicators (Power, Charging, Fault)"
    ],
},
{
    id: 1,
    name: "11kW AC  EV Charger",
    power: "11kW",
    type: "Type 2,1",
    price: "75,000",
    category: "AC",
    image: "11kw",
    available: true,
    src: img1,
    description: "The 11kW AC EV Charger is designed for residential and commercial use, offering a reliable and safe charging experience for electric vehicles. With its compact design, smart control features, and energy efficiency, this charger is ideal for home garages, offices, and small-scale EV charging networks.",
    specs: [
    "Output Power: 11 kW",
    "Output Voltage: 400V AC",
    "Output Current: 16A",
    "Connector Type: Type-2 (IEC 62196-2)",
    "Charging Mode: Mode 3 (IEC 61851)",
    "Communication Protocol: OCPP 1.6 JSON",
    "Network Connectivity: Wi-Fi / Ethernet / 4G (Optional)",
    "OEM: Ecoplug Energy India Limited",
    "Safety Features: Over-voltage, Over-current, Short Circuit, Surge, Ground Fault Protection",
    "Installation: Floor Mounting",
    "User Access: RFID / Mobile App / QR Code (Optional)",
    "Cable Length: 5m standard"
    ],
},
{
    id: 2,
    name: "15 kW AC (Hybrid) EV Charger – Ecoplug",
    power: "15 kW",
    price: "1,00,000",
    sku: "PROD-TJRJLZ",
    category: "ac",
    image: "15kw",
    available: "In Stock (50 units)",
    color: "White, Black",
    src: img2,
    description: "The Ecoplug 15 kW AC EV Charger is a high-capacity AC solution ideal for commercial EV charging stations, office buildings, and premium residential projects. Offering fast charging with smart control, it ensures a secure and seamless experience with multiple safety features and OCPP-based connectivity.",
    specs: [
    "Output Power: 15kW",
    "Output Voltage: 400V AC (Three Phase)",
    "Output Current: 22A",
    "Connector Type: Type-2 (IEC 62196-2)",
    "Charging Mode: Mode 3 (IEC 61851)",
    "Communication Protocol: OCPP 1.6 JSON",
    "Connectivity: Wi-Fi / Ethernet / 4G (Optional)",
    "OEM: Ecoplug Energy India Limited",
    "User Authentication: RFID / Mobile App / QR Code",
    "Protection Features: Over-voltage, Over-current, Short Circuit, Surge, Ground Fault",
    "Ingress Protection: IP54 / IP65",
    "Installation: Floor Mounting",
    "Operating Temp: -20°C to +55°C"
    ],
},
{
    id: 3,
    name: "15kW AC(Dual Gun) EV Charger",
    power: "15 kW",
    type: "Type 1,2",
    price: "1,00,000",
    sku: "PROD-2K8SXO",
    category: "AC",
    image: "15kw",
    available: "In Stock (50 units)",
    color: "Black, White",
    src: img3,
    description: "The Ecoplug 15kW AC EV Charger is a high-capacity AC solution ideal for commercial EV charging stations, office buildings, and premium residential projects. Offering fast charging with smart control, it ensures a secure and seamless experience with multiple safety features and OCPP-based connectivity.",
    specs: [
    "Output Power: 15kW",
    "Output Voltage: 400V AC (Three Phase)",
    "Output Current: 22A",
    "Connector Type: Type-2 (IEC 62196-2)",
    "Communication Protocol: OCPP 1.6 JSON",
    "Connectivity: Wi-Fi / Ethernet / 4G (Optional)",
    "OEM: Ecoplug Energy India Limited",
    "User Authentication: RFID / Mobile App / QR Code",
    "Protection Features: Over-voltage, Over-current, Short Circuit, Surge, Ground Fault",
    "Ingress Protection: IP54 / IP65",
    "Installation: Floor Mounting",
    "Operating Temp: -20°C to +55°C"
    ],
},
{
    id: 4,
    name: "6.6kW AC EV Charger(Two Smart Plug Socket)",
    power: "6.6kW",
    type: "Type 1,2",
    price: "50,000",
    sku: "PROD-6K6SMT",
    category: "AC",
    image: "6.6kw",
    available: "In Stock (50 units)",
    color: "White  Black",
    src: img4,
    description: "The 6.6 KW AC EV Charger is designed for residential and commercial use, offering a reliable and safe charging experience for electric vehicles. With its compact design, smart control features, and energy efficiency, this charger is ideal for home garages, offices, and small-scale EV charging networks.",
    specs: [
    "Output Power : 6.6 KW",
    "Output Voltage : 230V AC (Single Phase)",
    "Output Current: 14A – 32A (adjustable)",
    "Input Power : Input Voltage: 230V AC ±10%",
    "Frequency: 50/60Hz",
    "Input Current: 32 A",
    "Connector Type : Standard: Type-2 (IEC 62196-2)",
    "Cable Length: 5m standard (customizable)",
    "Charging Mode : Mode 3 (as per IEC 61851 standards)",
    "User Interface : LED Status Indicators (Power, Charging, Fault)",
    "Communication Protocol: OCPP 1.6 JSON",
    "Network Connectivity: Wi-Fi / Ethernet (Optional)",
    "OEM: Ecoplug Energy India Limited",
    "User Access: RFID / Mobile App (Optional)"
    ],
},
{
    id: 6,
    name: "3.3kW Single Socket AC Charger",
    power: "3.3 kW",
    type: "Type 1",
    price: "50,000",
    sku: "PROD-OJEWDS",
    category: "AC",
    image: "3.3kw",
    available: "In Stock (50 units)",
    color: "White, Black",
    src: img6,
    description: "The 3.3 kW AC EV Charger is designed for residential and commercial use, offering a reliable and safe charging experience for electric vehicles. With its compact design, smart control features, and energy efficiency, this charger is ideal for home garages, offices, and small-scale EV charging networks.",
    specs: [
    "Output Power: 3.3 kW",
    "Output Voltage: 230V AC (Single Phase)",
    "Output Current: 16A",
    "Connector Type: Normal Socket",
    "Communication Protocol: OCPP 1.6 JSON",
    "Network Connectivity: Wi-Fi / Ethernet / 4G (Optional)",
    "OEM: Ecoplug Energy India Limited",
    "Installation: Wall Mount",
    "User Access: RFID / Mobile App (Optional)",
    "Frequency: 50/60Hz",
    "Cable Length: 5m standard",
    "User Interface : LED Status Indicators (Power, Charging, Fault)"
    ],
},
{
    id: 7,
    name: "10kW Ecoplug Bharat AC Charger",
    power: "10 kW",
    type: "Type 3,2,1",
    price: "1,00,000",
    sku: "PROD-KJ1RYB",
    category: "AC",
    image: "10kw",
    available: "In Stock (50 units)",
    color: "White, Black",
    src: img7,
    description: "The Bharat AC Charger is a standardized electric vehicle (EV) charging solution developed for India, primarily designed for AC charging of electric two-wheelers, three-wheelers, and some four-wheelers. It operates with a 15A single-phase plug and supports charging at 3.3 kW power output, following the **Bharat AC-001** specification. It is suitable for public and private charging infrastructure, offering safe, reliable, and affordable EV charging.",
    specs: [
    "Input Voltage : 230 V ± 10%, Single Phase AC",
    "Input Frequency : 50 Hz ± 1.5 Hz",
    "Output Power : 3.3 kW (max per outlet)",
    "Output Voltage : 230 V AC",
    "Output Current : 15 A (max per outlet)",
    "Number of Outputs : 3 x 3.3 kW AC outputs",
    "Connector Type : IEC 60309 Industrial Socket (BS 546/IS 1293)",
    "Communication Protocol : OCPP 1.5 (Open Charge Point Protocol)",
    "Metering : Energy metering per outlet",
    "User Authentication : RFID-based / Mobile App / Other options",
    "Enclosure : IP55 (weather-proof)",
    "Mounting : Wall or pedestal mounted",
    "OEM : Ecoplug Energy India Limited"
    ],
}
];

export default products;
